name: Checkmarx AST Scan
on: [pull_request]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@AST-10425-fix-pr-branch-override #Github Action version
        with:
          project_name: TestGitHubAction_no_wait_mode
          base_uri: https://ast.ppe.cxast.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: research_tenant
