name: Checkmarx AST Scan
on:
  pull_request:
      branches:
        - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: testGHAction
          base_uri: https://deu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: cx_ast_rd_galatica_canary
          additional_params: --threshold sast-high=1