name: Workflow dispatcher
on:
  workflow_dispatch: 
    inputs: 
      Backfill:
        required: true
        type: boolean
      Main:
        required: true
        type: boolean  
      env:
        required: true
        type: string
      tag:
        required: true
        type: string  
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        if: ${{ contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }}
        run: echo 'Hello ${{ inputs.env }}!'