name: Workflow dispatcher
on:
  workflow_dispatch: 
    inputs: 
      pipeline:
        required: true
        type: choice
        description: Pipeline execution type
        options:
        - Backfill
        - Main
      if: ${{ inputs.pipeline === 'Main' }}  
      env:
        required: true
        type: string
      if: ${{ inputs.pipeline === 'Backfill'}}
      tag:
        required: true
        type: string  
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        if: ${{ contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }}
        run: echo 'Hello ${{ inputs.env }}!'