name: Workflow dispatcher
on:
  workflow_dispatch: 
    inputs: 
      Backfill:
        required: true
        type: boolean
      Main:
        required: true
        type: boolean  
      env:
        required: false
        type: string
      tag:
        required: false
        type: string  

env:
  isValidEnv:  ${{ contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }}       
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check valid environment
        if: env.isValidEnv
        run: echo 'Hello ${{ inputs.env}}'  

      - name: Invalid environment check
        if: !env.isValidEnv
        run: echo 'Invalid environment'  