name: Workflow dispatcher
on:
  workflow_dispatch: 
    inputs: 
      Backfill:
        required: true
        type: boolean
      Main:
        required: true
        type: boolean  
      env:
        required: false
        type: string
      tag:
        required: false
        type: string  
       
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invalid environment
        if: ${{ !contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }} 
        run: |
        echo "Invalid environment"
        exit 1

      - name: Validate deployment type
        if: ${{ !inputs.Backfill && !inputs.Main}}  
        run: |
        echo "Select either Backfill or main"
        exit 1